### ISSUE TITLE
Error: HopApi > Error on request '/tx/compile' : Bad Request

### ISSUE THREAD

**Issue by kwokholee5** [hopaggregator/sdk#7]
Error: HopApi > Error on request '/tx/compile' : Bad Request
    at makeAPIRequest (file:///C:/Users/Admin/WebstormProjects/omnimev-sui/node_modules/@hop.ag/sdk/dist/esm/sdk/util.js:21:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchTx (file:///C:/Users/Admin/WebstormProjects/omnimev-sui/node_modules/@hop.ag/sdk/dist/esm/sdk/routes/tx.js:110:22)
    at async executeTradeIfProfitable (file:///C:/Users/Admin/WebstormProjects/omnimev-sui/index.js:30:27)
    at async monitorAndExecuteTrades (file:///C:/Users/Admin/WebstormProjects/omnimev-sui/index.js:123:13)

error received with swap function in the example code.  any idea?

**Comment by binhnguyen2501** [comment]
I got the same issue too!
